CREATE TABLE public.product_images (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    menu_item_id bigint NOT NULL,
    image_url text NOT NULL,
    CONSTRAINT product_images_pkey PRIMARY KEY (id),
    CONSTRAINT product_images_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items (id) ON DELETE CASCADE
);

ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to product images" ON public.product_images FOR SELECT USING (true);

CREATE POLICY "Allow owners to manage their product images" ON public.product_images FOR ALL
USING (
  ( SELECT auth.uid() = user_id
    FROM public.catalogs c
    JOIN public.menu_items mi ON mi.catalog_id = c.id
    WHERE mi.id = product_images.menu_item_id
  )
)
WITH CHECK (
  ( SELECT auth.uid() = user_id
    FROM public.catalogs c
    JOIN public.menu_items mi ON mi.catalog_id = c.id
    WHERE mi.id = product_images.menu_item_id
  )
);
