-- Add views_count to catalogs table
ALTER TABLE catalogs ADD COLUMN IF NOT EXISTS views_count INTEGER DEFAULT 0 NOT NULL;

-- Create store_visits table
CREATE TABLE IF NOT EXISTS store_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_id BIGINT REFERENCES catalogs(id) ON DELETE CASCADE NOT NULL,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  session_id TEXT
);

-- Enable RLS
ALTER TABLE store_visits ENABLE ROW LEVEL SECURITY;

-- Policies for store_visits
CREATE POLICY "Anyone can insert store visits." ON store_visits
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Owners can select their own store visits." ON store_visits
  FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM catalogs WHERE catalogs.id = store_visits.catalog_id AND catalogs.user_id = auth.uid()
  ));

-- Create function to increment visits
CREATE OR REPLACE FUNCTION increment_store_visit(p_catalog_id bigint, p_session_id text)
RETURNS void AS $$
BEGIN
  -- Update the cached count in catalogs
  UPDATE catalogs
  SET views_count = views_count + 1
  WHERE id = p_catalog_id;

  -- Insert visit record
  INSERT INTO store_visits (catalog_id, session_id)
  VALUES (p_catalog_id, p_session_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
